### PR TITLE
The Trie PR

### PR DESCRIPTION
**Pull request by atalii**
As promised and complained about, here's a PR that uses a trie to prefix-match pronouns. As it stands, this changes two behaviors:

1. The API endpoint to look up a pronoun will return a list of *all matching pronouns* rather than *whichever is first in the HashMap*. As the HashMap doesn't guarantee an order of iteration, this resolves some undefined behavior. (I think I need to update the API docs to reflect this change.)
2. We can use a single `...` in URLs to act as wildcards. `/they/.../themself` and `/they/.../themselves` work as expected. My solution isn't perfect here, see 502ceb43.

The code is rough around the edges and the API docs are probably out of date, but I figured I'd open the PR now and give you a chance to look through it and suggest changes before I start polishing. Thanks!

### CODE REVIEW

**Comment by atalii** [comment]
Alright, code should be a bit better now. *Might* be merge-able barring oversights and feedback. This significantly cuts down on the number of weird hacks, only introduces a few of its own, is a bit more flexible, and (at least in terms of time complexity) faster. A few things I'd be concerned about:

* It's possible that the TST is initialized in sorted order, which is sort of a pathological case the same way it would be for a binary tree. I don't know what the exact behavior is, and I haven't actually checked, but randomizing the Vec<PronounSet> we initialize from might be worth it if this is the case and lookup seems slow. (In terms of time-complexity, this pathological case is actually still better than the hash table, but cache utilization is worse, so  ¯\_(ツ)_/¯.)
* It also might be worth it to memoize `PronounTrie::gather` which has to do a whole song and dance every time someone reuqests all the pronouns. Time complexity here (`O(m * n)`) is a bit worse than the hash table's linear gather. I've never worked on a production web service, though, so your intuition here is going to be way better than mine.

Anyway, thanks for reviving pronoun.is, it was very useful and I'm happy to have a successor!

**Comment by Xe** [comment]
The only problem I see with this is that the order of the all pronouns list on the website is consistently unsorted.

Screenshot 2023-01-08 at 09 47 24

Other than that this looks great so far! Gonna do a small bit of "acceptance" testing and might just yolo this into prod for the lulz.

**Review by Xe — APPROVED** [review]
The best kind of kill is overkill

**Comment by atalii** [comment]
Everything's sorted now, I can hear my algorithms textbook cringing at that mistake. Anyway, tell if me I missed anything else, thanks!

**Comment by Xe** [comment]
Looks good to me! Yolo!

**Comment by Xe** [comment]
It looks like this is causing memory leaks on every request. Here is a DHAT dump of a lot of requests: https://gist.githubusercontent.com/Xe/cda192a132421d69d12359d0b5953d1d/raw/3b2e37feefe5ecb4121be82c64fdcf64999a8923/gistfile1.txt

Seems that the cloning is using a lot of memory but I'm not sure how to turn that into a fix.

**Comment by atalii** [comment]
Oh, lovely; thanks for letting me know. I'm wading through my school's finals right now, but I'll see if I can find some time tonight (MDT) to look it over and find a fix.

**Comment by atalii** [comment]
Before looking at the profile data, I just wrapped up the PronounTrie state in an Arc and removed the clone derivations (5007dc91). This had no effect. Doing things right and profiling found the culprit to be... titlecase. Yeah, uh, what? Here are some screenshots of the heap usage over time graphs before and after removing the calls to titlecase.

with titlecase

without titlecase

Digging further into the traces, it seems that the culprit appears to be some regex's somewhere. I suspect there's something tricky going on with the allocator, but I honestly have no particular interest in digging through it all at the moment. I just swapped it out for a different library (6423d03496fe9, heck) which doesn't seem to leak. Anyway, thanks for pointing this out, and do let me know if I've missed anything.

**Pull request merged**
